version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: spaceapps-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: spaceapps
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
